### ISSUE TITLE
CDW  Sprint 2/1 Planning

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/service-and-facility-locator#14]

**Comment by rickleegit** [comment]
@department-of-veterans-affairs/facilities-locator-post-11-11-2015: Placeholder for 2/1 Sprint Planning

**Comment by rickleegit** [comment]
Need input on GEO BISL MOA from @koconnor719

**Comment by koconnor719** [comment]
Rick as soon as i'm briefed on the memo i'm happy to give input.  i don't have any context or background at this point--just questions.  i suggest we have a quick review on this--pls. include @ayaleloehr  . thank you.

**Comment by rickleegit** [comment]
Can you attend the noon meeting today? We could review then.

**Comment by koconnor719** [comment]
yes
Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436
