### ISSUE TITLE
Get handle on what data/background Linda provided Wk 1 (Alex: 8, Rick:8)

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/service-and-facility-locator#17]
There is a lot of data.  Tasks likely include:

[ ] Read supporting Word documents about data sources
[ ] Manually examine Excel file with services
[ ] Is the taxonomy complete?
[ ] Figure out how to join data with VAST

**Comment by rickleegit** [comment]
- [x] Review to confirm existence or gap in Mental health data and POCs.
