### ISSUE TITLE
Current prototype non-UX issues

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/service-and-facility-locator#44]
- [x] VBA data needs to be input and searchable
- [ ] links to current facility pages on va.gov need to be added to the data set then to facility detail page

**Comment by rickleegit** [comment]
@ayaleloehr 

Show Page:
- [x] It JUST dawned on me that Service L1 can not be a multi-select. Can you change it to a drop-down? Sorry, 
- [x] Need toggle for non-VA providers. Checkbox would work and I will style something. 
- [x] Would be nice to have a result count somewhere. 
- [ ] Need non-VA data added. 
- [x] Entire list displays on "show" page. No filtering appears to be applied.
- [x] I have no idea where to apply styling to the list of facilities
- [x] Facilities data list is not complete (see pdf attached)
- [x] Rollover interactions data not complete (see pdf attached)
- [x] Refinement filtering not applying.
- [x] I added static active breadcrumbs but they don't do anything. Should toggle filters.
- [x] Driving Distances from epicenter in pins
- [x] Address searched does not populate in the text field when you arrive at 'show' page.
- [x] The map and the list are not aligned. The list should only show facilities that are represented on the map. This will need to change by zoom level.
- [x] I created a custom styled map, but have no idea how to implement it. 

Details page is pretty passable for Friday. 

[Clarity Diagram.pdf](https://github.com/department-of-veterans-affairs/service-and-facility-locator/files/155968/Clarity.Diagram.pdf)

**Comment by ayaleloehr** [comment]
Added in issues for the two boxes left unchecked. Closing this in favor of the more specific issues.
