### ISSUE TITLE
Current prototype UX issues

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/service-and-facility-locator#45]
Trying to jot down what I see as the open UX issues with the code I just merged and put who I think should be in charge of each next to each item (A = @ayaleloehr, R = @rickleegit ).  Feel free to either add other comments or just edit this one to add whatever I missed.
- [x] R: Initial page styling
- [x] R: Map view page styling 
  - currently have filters at top, but feel free to move). 
  - Also should probably have list of facilities along the left side?
- [x] R: Detail page styling 
  - I messed up hours of operation styling by trying to change the "hours note"
  - Each SL1 now only shown once. 
- [ ]  A or R: When you get to the map page, SL1 and SL2 are not properly highlighted in their filter boxes
- [ ] A or R: Hitting "enter" after typing a location should search
- [ ]  A: Pins should be colored based on the facility classification
  - Classifications are VA Medical Center (VAMC), Residential Care Site, Extended Care Site, and everything else in VHA falls under VA Clinic
- [x] A: Pins should have a more useful popup text when you click on them
- [x] A: Only facilities that are currently in the map view should show up
- [ ] R?: breadcrumbs are always displaying "Service and Facility Locator"
  - I think on the search page we want it to have the Service Levels that are being filtered by?
  - I think on the detail page we want it to have the facility name?

**Comment by rickleegit** [comment]
@ayaleloehr A couple of things:

I took R's off of tasks that I can't do on my own and will need you to accomplish or assist. 

This one: breadcrumbs are always displaying "Service and Facility Locator"
as long as this is in a partial, we can't really do much with it.

**Comment by ayaleloehr** [comment]
@rickleegit ^^ took breadcrumbs out of the partial (deleted the file the partial was defined in even, actually) in the code I checked into `master` last night.

**Comment by rickleegit** [comment]
OK I will play with it and see if I can make it happen.

**Comment by rickleegit** [comment]
@ayaleloehr: I merged the branch 0302FE into master and deleted the branch. 

Today I am focused on getting the refinement menu working. It is currently not working properly.
