### ISSUE TITLE
Facility on map not in list

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/service-and-facility-locator#52]
This facility shows on the map, but does not show in the list (no it is not a scrolling PEBKAC issue)

<img width="1471" alt="screen shot 2016-03-04 at 6 35 01 am" src="https://cloud.githubusercontent.com/assets/11138830/13526079/8fa92a64-e1d3-11e5-9e37-3915f516045c.png">

**Comment by ayaleloehr** [comment]
@rickleegit can you see if this still happens after the update this morning?
